const DataDokter = [
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
    {
        no_dokter: Math.random().toString(36).slice(2),
        name: "rudi suwarno",
        role_dokter: "spesialis tulang lunak",
        klinik: "ortopedi",
        biaya_penanganan: "1.000.000",
        jam_praktek: "10.00 - 16.00",
    },
]

export default DataDokter