<<<<<<< HEAD
const dataPasien = [
    {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    },
       {
        jenisKunjungan: "Jenguk",
        keluhan: "Batuk",
        namaPasien: "Agung",
        namaPjPasien: "Antok",
        tanggalMasuk: "18 January 2024",
        pembayaran: "Qris",
        Status: "Baru"
    }
]
=======
const DataPasien = [
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
];

export default DataPasien;
>>>>>>> 7420451127f9ef414f916634dcd0090049f3bab1
