const DataPasien = [
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Pria",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "BPJS",
  },
  {
    nomorpasien: Math.random().toString(36).slice(2),
    namaPasien: "Nama Pasien",
    jenisKunjungan: "Jenis Kunjungan",
    jenisKelamin: "Wanita",
    keluhan: "Keluhan",
    poli: "Poli",
    waktuKunjungan: "Waktu Kunjungan",
    nomorTelepon: "No telpon",
    tipe: "Umum",
  },
];

export default DataPasien;