const DataKonter = [
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },

  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },

  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },

  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },

  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi indah blok A no.7, ngemplak, sleman, yogyakarta",
  },
  {
    no_konter: Math.random().toString(36).slice(2),
    type: "Asuransi",
    name: "gedung 1",
    operational: "Jam operasional",
    address: "jalan raya candi gebang blok A no.7, ngemplak, sleman, yogyakarta",
  },
];

export default DataKonter;
