const DataPegawai = [
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "maliha david firdaus",
        role: "dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "himawan fauzi ramadhan",
        role: "asisten dokter",
        menuAkses: "dashboard dokter",
        detailAkses: "view, update, delete",
    },
    {
        nip: Math.random().toString(36).slice(2),
        name: "surya pratama",
        role: "admin",
        menuAkses: "dashboard admin",
        detailAkses: "view, update, delete",
    },
]

export default DataPegawai